services:
  - type: web
    name: quick-commerce-medicine-api
    env: python
    buildCommand: |
      cd backend
      python --version
      pip install --upgrade pip setuptools wheel
      export CRYPTOGRAPHY_DONT_BUILD_RUST=1
      export CARGO_NET_OFFLINE=true
      pip install --only-binary=:all: --prefer-binary -r requirements.txt
      alembic upgrade head
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    runtime: python311
    envVars:
      - key: CRYPTOGRAPHY_DONT_BUILD_RUST
        value: "1"
      - key: PIP_ONLY_BINARY
        value: "cryptography,bcrypt,cffi"
      - key: DATABASE_URL
        value: sqlite:///./quick_commerce_medicine.db
      - key: SECRET_KEY
        generateValue: true
      - key: PROJECT_NAME
        value: Quick Commerce Medicine Delivery API
      - key: API_V1_STR
        value: /api/v1
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 11520
      - key: REFRESH_TOKEN_EXPIRE_MINUTES
        value: 43200
      - key: BACKEND_CORS_ORIGINS
        value: '["https://mediquick-frontend.vercel.app","http://localhost:5173","https://localhost:5173"]'
      - key: FIRST_SUPERUSER
        value: admin@quickcommerce.com
      - key: FIRST_SUPERUSER_PASSWORD
        generateValue: true

# Using SQLite for simplicity - no external database needed
