services:
  - type: web
    name: quick-commerce-medicine-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: quick-commerce-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PROJECT_NAME
        value: Quick Commerce Medicine Delivery API
      - key: API_V1_STR
        value: /api/v1
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 11520
      - key: REFRESH_TOKEN_EXPIRE_MINUTES
        value: 43200
      - key: BACKEND_CORS_ORIGINS
        value: https://your-frontend-domain.com
      - key: FIRST_SUPERUSER
        value: admin@quickcommerce.com
      - key: FIRST_SUPERUSER_PASSWORD
        generateValue: true

databases:
  - name: quick-commerce-db
    databaseName: quick_commerce_medicine_db
    user: quick_commerce_user
    plan: free
