"""Add cancellation_reason to orders

Revision ID: ad46644f4391
Revises: 2e7a605034a0
Create Date: 2025-07-14 11:22:08.978878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad46644f4391'
down_revision: Union[str, Sequence[str], None] = '2e7a605034a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancellation_reason')
    # ### end Alembic commands ###
